name: Run action tests

on: [ push ]

jobs:
  action-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get next release version
        id: next_release
        uses: martinsbalodis/ga-next-patch-release@master
        with:
          base_release: 0.1.0

      - name: Print next release
        run: echo ${{ steps.next_release.outputs.nextRelease }}

      - name: Assert next release
        run: |
          [[ "${{ steps.next_release.outputs.nextRelease }}" == 0.1.1 ]]
